language: "perl"
before_install:
    - perl Makefile.PL | cpanm
install:
    - cpanm --notest --verbose --installdeps .
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
